package uk.gegc.quizmaker.dto.quiz;

import io.swagger.v3.oas.annotations.media.Schema;
import uk.gegc.quizmaker.model.question.QuestionType;

import java.time.Duration;
import java.util.Map;

@Schema(name = "QuizGenerationSummary", description = "Summary of the quiz generation process")
public record QuizGenerationSummary(
        @Schema(description = "Total number of chunks in the document", example = "5")
        Integer totalChunks,

        @Schema(description = "Number of chunks successfully processed", example = "5")
        Integer successfulChunks,

        @Schema(description = "Number of chunks that failed processing", example = "0")
        Integer failedChunks,

        @Schema(description = "Number of questions generated by type", example = "{\"MCQ_SINGLE\": 15, \"TRUE_FALSE\": 10}")
        Map<QuestionType, Integer> questionsByType,

        @Schema(description = "Average questions generated per chunk", example = "5.0")
        Double averageQuestionsPerChunk,

        @Schema(description = "Total processing time", example = "PT2M30S")
        Duration totalProcessingTime
) {} 